export const ALERT_FROM_CART = "ALERT_FROM_CART"

export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const ADD_TO_CART = "ADD_TO_CART"

export const ADD_TO_CART_SAGA = "ADD_TO_CART_SAGA"
export const REMOVE_FROM_CART_SAGA = "REMOVE_FROM_CART_SAGA"


export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_SAGA = "GET_PRODUCT_SAGA"







